name: ytb
channels:
  - pyg
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cython
  - pip:
    - jupyterlab
    - jupytext
    - pyarrow
    - boto3==1.26.133
    - choix==0.3.5
    - emoji==2.2.0
    - Faker==15.3.4
    - fastnode2vec==0.0.6
    - fbpca==1.0
    - google-api-python-client==2.86.0
    - gspread==5.7.2
    - hdbscan==0.8.28
    - innertube==2.1.0
    - ipython==8.4.0
    - ipywidgets==7.6.5
    - jmespath==1.0.1
    - joblib==1.2.0
    - kneebow==1.0.1
    - kneed==0.8.1
    - matplotlib==3.6.0
    - networkx==2.8.8
    - numpy==1.23.4
    - optuna
    - pandas==1.5.0
    - plotly==5.10.0
    - polars==0.14.17
    - pyspark==3.3.0
    - PyYAML==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - scikit-learn==1.1.2
    - scipy==1.10.0
    - seaborn==0.12.0
    - sentence-transformers==2.2.2
    - statsmodels==0.13.5
    - tqdm==4.64.1
    - tsmoothie==1.0.4
    - urllib3==1.26.11
    - umap-learn==0.5.3  
    - whatthelang==1.0.1
